[formatter.yamlfmt]
command = "yamlfmt"
includes = ["*.yaml", "*.yml"]

[formatter.nixfmt]
command = "nixfmt"
includes = ["*.nix"]

[formatter.typstyle]
command = "typstyle"
options = ["--inplace"]
includes = ["*.typ"]