name: Build with Nix
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - master
jobs:
  build-document:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - ubuntu-24.04-arm
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout tree
        uses: actions/checkout@v5
      - name: Install Nix
        uses: DeterminateSystems/determinate-nix-action@main
      - name: Build the document
        run: nix run .#build-lecture-notes
  flake-check:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - ubuntu-24.04-arm
          - macos-latest
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout tree
        uses: actions/checkout@v5
      - name: Install Nix
        uses: DeterminateSystems/determinate-nix-action@main
      - name: Check Flake
        run: nix flake check
